name = "davidtech-update-worker"
main = "src/index.js"
compatibility_date = "2025-11-01"
workers_dev = false

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "davidtech-app-updates"

[[routes]]
pattern = "updates.davidtechllc.com"
custom_domain = true

[observability]
enabled = true
